# Generated by Django 4.2.6 on 2023-10-12 22:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Ingresa el título del proyecto.', max_length=200)),
                ('summary', models.TextField(default='', help_text='Ingresa una descripción de la inversión.', max_length=1000)),
                ('mini_summary', models.TextField(default='', help_text='Ingresa una descripción breve de la inversión. No más de 50 carácteres.', max_length=50)),
                ('company', models.CharField(help_text='Ingresa el nombre de la compañía que dirige el proyecto.', max_length=200)),
                ('date_published', models.DateField(blank=True, help_text='Fecha de publicación.', null=True)),
                ('interest_rate', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
            ],
            options={
                'permissions': (('can_add_project', 'Puede añadir proyecto'),),
            },
        ),
        migrations.CreateModel(
            name='ProjectInstance',
            fields=[
                ('date_acquired', models.DateField(blank=True, help_text='Fecha de unión al proyecto', null=True)),
                ('date_of_end_contract', models.DateField(blank=True, help_text='Fecha de fin de unión al proyecto', null=True)),
                ('investment', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('rate_time', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'permissions': (('can_add_instance_project', 'Puede añadir inversión'),),
            },
        ),
    ]
