# Generated by Django 4.2.6 on 2023-10-11 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_add_project', 'Puede añadir proyecto'),)},
        ),
        migrations.AlterModelOptions(
            name='projectinstance',
            options={'permissions': (('can_add_instance_project', 'Puede añadir inversión'),)},
        ),
        migrations.AlterField(
            model_name='projectinstance',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
