# Generated by Django 4.2.6 on 2023-10-11 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('project', '0003_alter_project_id_alter_projectinstance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinstance',
            name='investor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
